"""ECHO Action + Reliability Core v1 — Conversation Auto-Summary.

A compact, decision-oriented summary of a conversation, generated by the
local model (same ScriptedProvider-testable pattern as
local_intelligence_engine.py's critic pass) with a deterministic,
no-model-call fallback so this never hard-fails just because Ollama is
unreachable. Never stores raw prompt/debug text — only the parsed summary
fields end up in the DB.
"""

import json
import logging
import re

from sqlalchemy.orm import Session

from app.config import get_settings
from app.models import Conversation, ConversationSummary, Message
from app.providers.base import ChatMessage
from app.services.local_model_router import LocalModelRouter

logger = logging.getLogger(__name__)

_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)

_SUMMARY_PROMPT = """Summarize this conversation. Respond with ONLY a single JSON object, no other text, no markdown fences.

CONVERSATION:
{transcript}

Respond with exactly this JSON shape:
{{"title": "short title", "summary": "2-4 sentence summary", "decisions": ["short strings"], \
"tasks": ["short strings"], "open_questions": ["short strings"], "next_steps": ["short strings"]}}

Only include real, specific items — use an empty list if there genuinely aren't any. Never invent \
a decision or task that wasn't actually discussed."""


def _parse_summary_json(raw: str) -> dict | None:
    if not raw:
        return None
    match = _JSON_BLOCK_RE.search(raw)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(parsed, dict):
        return None
    return parsed


def _transcript_for(messages: list[Message], max_chars: int = 6000) -> str:
    lines = [f"{m.role}: {m.content}" for m in messages]
    text = "\n".join(lines)
    return text[-max_chars:] if len(text) > max_chars else text


def _deterministic_fallback(conversation: Conversation, messages: list[Message]) -> dict:
    """No model call, no fabrication — just the conversation title and a
    plain notice that a real summary couldn't be generated right now."""
    return {
        "title": conversation.title,
        "summary": f"{len(messages)} message(s) in this conversation. A local-model summary wasn't available when this was generated.",
        "decisions": [],
        "tasks": [],
        "open_questions": [],
        "next_steps": [],
    }


def summarize_conversation(db: Session, conversation_id: str) -> ConversationSummary | None:
    conversation = db.get(Conversation, conversation_id)
    if conversation is None:
        return None
    messages = db.query(Message).filter(Message.conversation_id == conversation_id).order_by(Message.created_at).all()
    if not messages:
        return None

    router = LocalModelRouter()
    result = router.call(
        "fast", "You produce structured conversation summaries only.", [ChatMessage(role="user", content=_SUMMARY_PROMPT.format(transcript=_transcript_for(messages)))]
    )
    parsed = _parse_summary_json(result.text) if result.ok else None
    data = parsed or _deterministic_fallback(conversation, messages)

    existing = db.query(ConversationSummary).filter(ConversationSummary.conversation_id == conversation_id).first()
    row = existing or ConversationSummary(conversation_id=conversation_id)
    row.title = str(data.get("title") or conversation.title)[:200]
    row.summary = str(data.get("summary") or "")
    row.decisions_json = [str(x) for x in (data.get("decisions") or [])][:10]
    row.tasks_json = [str(x) for x in (data.get("tasks") or [])][:10]
    row.open_questions_json = [str(x) for x in (data.get("open_questions") or [])][:10]
    row.next_steps_json = [str(x) for x in (data.get("next_steps") or [])][:10]
    row.memories_to_review_json = []
    if existing is None:
        db.add(row)
    db.commit()
    db.refresh(row)
    return row


def get_summary(db: Session, conversation_id: str) -> ConversationSummary | None:
    return db.query(ConversationSummary).filter(ConversationSummary.conversation_id == conversation_id).first()


def should_auto_summarize(db: Session, conversation_id: str) -> bool:
    settings = get_settings()
    if not settings.conversation_auto_summary_enabled:
        return False
    count = db.query(Message).filter(Message.conversation_id == conversation_id).count()
    return count >= settings.conversation_auto_summary_min_messages


def summary_to_knowledge_item(db: Session, summary: ConversationSummary):
    from app.services import knowledge_vault

    body_parts = [summary.summary]
    if summary.decisions_json:
        body_parts.append("Decisions: " + "; ".join(summary.decisions_json))
    if summary.next_steps_json:
        body_parts.append("Next steps: " + "; ".join(summary.next_steps_json))
    return knowledge_vault.create_item(
        db,
        title=summary.title or "Conversation summary",
        body="\n\n".join(body_parts),
        item_type="summary",
        source_type="conversation",
        source_id=summary.conversation_id,
        tags=["conversation-summary"],
        confidence="medium",
    )
